pipeline {
    agent {
        docker {
            image 'node:10-alpine'
        }
    }
    environment {
        HOME = '.'
        AWS_REGION = 'us-east-1'
        BUCKET_NAME = 'graphql-subscribe-lambda'
        ZIP_NAME = 'graphql-lambda.zip'
        NODE_ENV = 'production'
    }
    stages {
        stage('Install') {
            steps {
                sh 'npm install --production'
            }
        }
        stage('ZIP') {
            steps {
                zip zipFile: env.ZIP_NAME, archive: false, dir: '/'
            } 
        } 
        stage('Deploy') {
            steps {
                withAWS(region: env.AWS_REGION, credentials: '1') {
                    s3Delete(bucket: env.BUCKET_NAME, path: '/')
                    s3Upload(bucket: env.BUCKET_NAME, file: env.ZIP_NAME);
                }
            }
        }
    }
}