pipeline {
    agent {
        docker {
            image 'node:10-alpine'
        }
    }
    environment {
        HOME = '.'
        AWS_REGION = 'us-east-1'
        BUCKET_NAME = 'graphql-subscribe-lambda'
        NODE_ENV = 'production'
    }
    stages {
        stage('Install') {
            steps {
                sh 'npm install --production'
            }
        }
        stage('Deploy') {
            steps {
                step([
                    $class: 'S3BucketPublisher', 
                    consoleLogLevel: 'INFO', 
                    dontWaitForConcurrentBuildCompletion: false, 
                    entries: [[
                        bucket: 'graphql-subscribe-lambda', 
                        excludedFile: '', 
                        flatten: false, 
                        gzipFiles: true, 
                        keepForever: false, 
                        managedArtifacts: false, 
                        noUploadOnFailure: false, 
                        selectedRegion: env.AWS_REGION, 
                        showDirectlyInBrowser: false, 
                        sourceFile: '*/**', 
                        storageClass: 'STANDARD', 
                        uploadFromSlave: false, 
                        useServerSideEncryption: false
                    ]], 
                    pluginFailureResultConstraint: 'FAILURE',
                    profileName: 'Jenkins', 
                    userMetadata: []
                ])
            }
        }
    }
}